# Generated by Django 2.1.2 on 2018-10-15 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_basic-question-model'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'question_link',
            },
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
        migrations.AddField(
            model_name='questionlink',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='backend.Question'),
        ),
        migrations.AddField(
            model_name='questionlink',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='backend.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='linked_questions',
            field=models.ManyToManyField(through='backend.QuestionLink', to='backend.Question'),
        ),
    ]
